### ISSUE TITLE
This works right?

### ISSUE THREAD

**Issue by faddat** [Ikuu/vue-reddit#1]
It looks like all is in order, and I'm going to use it to hook up to a content blockchain.  if you are interested I'm very happy to show you the ropes while I do it.  Timeframe: next 8 or so hours.  Platform: faddat@gmail.com on google hangouts

**Comment by Ikuu** [comment]
Yea it works but it's very basic, just grabs the first page of a subreddit, can click into posts but they show very little at the moment.
